name: Run

on:
  workflow_dispatch:
    inputs:
      wsuId:
        description: 'Your WSU ID'
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Python
        uses: actions/setup-python@v3
        with:
          version: '3.10'

      - name: Install Requirements
        run: python3 -m pip install -r requirements.txt

      - name: Run Command
        run: python3 main.py ${{ github.event.inputs.wsuId }}
